steps:
- run: cd portfolio
  name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'mvn'
  args: ['clean']

- run: cd portfolio
  name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'mvn'
  args: ['package', 'appengine:deploy'] 