steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'mvn'
  args: ['clean']
  dir: portfolio

- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'mvn'
  args: ['package', 'appengine:deploy']
  dir: portfolio
